j2kun/lonely-hearts

.env.template, .gitignore, README.md, app.py, requirements.txt
=> mongo: add mongodb

hearts/hearts.py, hearts/tests/test_hearts.py
This PR implements the `Card` class and converts the existing code and tests to use it.
=> hearts: add Card class

hearts/hearts.py, hearts/tests/fake.py, hearts/tests/test_hearts.py, tests/test_style.py
Cleaning up tests a little bit.
=> Jeremy cleanup tests

README.md, app.py, env.template, settings.py
Fixes https://github.com/j2kun/lonely-hearts/issues/25
This PR sets up the use of a `.env` file so that Daniel and I can maintain separate configuration variables with the same code. See the updated section of the README for instructions, and take a look at `settings.py` (and how it's imported and used in `app.py`).
=> api: setup env vars

hearts/hearts.py, hearts/tests/fake.py, hearts/tests/test_hearts.py
https://github.com/j2kun/lonely-hearts/issues/15
=> hearts.py: Update the game when hearts break

static/room.js, templates/room.html
Fixes https://github.com/j2kun/lonely-hearts/issues/21
To see it in action, run `python app.py`, with your custom `.env` configured, open the app in the browser, and try clicking on a card.
=> www/room: add play card logic and simple display

hearts/hearts.py, hearts/tests/test_hearts.py
Fixes https://github.com/j2kun/lonely-hearts/issues/27
=> hearts.py:  fixed the trick length bug and added unit test

.coveragerc, .travis.yml, README.md, requirements.txt, tox.ini
This PR adds automated test coverage. To get it working, simply re-run 
```
pip install -r requirements.txt
``` 
from inside your virtualenv (after this is merged). Then the next time you run `py.test` you'll see a nice test report like the following:
```
hearts/tests/test_hearts.py::test_card_serialize PASSED
hearts/tests/test_hearts.py::test_card_validate PASSED
hearts/tests/test_hearts.py::test_hand PASSED
hearts/tests/test_hearts.py::test_hand_sort PASSED
hearts/tests/test_hearts.py::test_serialize_hand PASSED
hearts/tests/test_hearts.py::test_trick_length PASSED
hearts/tests/test_hearts.py::test_trick_winner PASSED
hearts/tests/test_hearts.py::test_trick_leader PASSED
hearts/tests/test_hearts.py::test_serialize PASSED
hearts/tests/test_hearts.py::test_deal PASSED …
```
=> tests: add code coverage

hearts/tests/test_hearts.py
This PR addresses https://github.com/j2kun/lonely-hearts/issues/30.
=> test_hearts:  test_follow_the_trick() and play_card()

hearts/hearts.py, hearts/tests/fake.py, hearts/tests/test_round.py, hearts/tests/test_trick.py
This PR addresses https://github.com/j2kun/lonely-hearts/issues/17
=> hearts: add scoring to a round

hearts/tests/test_round.py
Implements the remainder of https://github.com/j2kun/lonely-hearts/issues/16
=> hearts/tests: randomized test of full round

hearts/hearts.py, hearts/tests/fake.py, hearts/tests/test_round.py
https://github.com/j2kun/lonely-hearts/issues/37:  Write a `pass_cards()` function in Round and make tests for it in test_round.py
=> hearts: add pass_cards()

.coveragerc, .travis.yml, conftest.py, tests/test_database.py
Implements https://github.com/j2kun/lonely-hearts/issues/40
=> tests: add conftest.py

docker-compose.yaml, nginx/Dockerfile, nginx/sites-enabled/hearts
Implements https://github.com/j2kun/lonely-hearts/issues/46
Now `docker-compose up` includes an nginx container.
=> backend: add nginx forwarding

api/README.md, api/tests/test_rooms_api.py, app.py, conftest.py, env.template, settings.py, templates/index.html, templates/socketio-example.html, tests/utils.py
This PR creates a REST endpoint that allows the user to create and enter a new room.
=> api: create a new room

app.py, conftest.py, env.template, settings.py, templates/index.html, templates/room.html
Addresses https://github.com/j2kun/lonely-hearts/issues/53
Blocked by https://github.com/j2kun/lonely-hearts/pull/52
=> api: reorganize configs

hearts/hearts.py, hearts/tests/fake.py, hearts/tests/test_game.py, hearts/tests/test_round.py
This PR addresses https://github.com/j2kun/lonely-hearts/issues/42
=> Implement the Game class

hearts/hearts.py, hearts/tests/fake.py, hearts/tests/test_game.py
https://github.com/j2kun/lonely-hearts/issues/58
=> tests: Add tests for deserializing Game

conftest.py, hearts/api/socket_events.py, hearts/api/tests/test_rooms_api.py
Implements https://github.com/j2kun/lonely-hearts/issues/61
This PR gives an example of how to test an action happening as a result of a socket event.
Aside from mostly refactoring names, the central part of the PR is https://github.com/j2kun/lonely-hearts/pull/66/files#diff-c74758396fa10cd37eacdb7d0dfdee8bR18
=> api/tests: example unit tests for socket events

README.md
=> Changing python app.py to run.py

env.template, hearts/__init__.py, hearts/api/rest_views.py, hearts/settings.py, run.py
- Add `DEBUG` config var, which when true will instantly restart the server when a file changes
- Configure the logger, so that we can put logging statements in the views.
=> settings: add DEBUG variable and logging

env.template, hearts/settings.py, hearts/templates/index.html
Try this branch on cloud 9 with settings:
```
WWW_HOST=<workspace_name>-<username>.c9users.io
HOST=0.0.0.0
PORT=8080
DATABASE_URL=mongodb://localhost:27017/hearts
DEBUG=True
```
=> settings: add WWW_HOST

hearts/api/rest_views.py, hearts/api/rooms.py
In `rooms.py`:
- `create_room`
- `get_room`
Notably, `get_room` allows the input to be a string or an ObjectId.
=> api: refactor rooms

hearts/game/hearts.py, hearts/game/tests/test_round.py
Implements https://github.com/j2kun/lonely-hearts/issues/82
=> hearts: serialize for player

hearts/api/games.py, hearts/api/socket_events.py, hearts/api/tests/test_socket_events.py
in `socket_events.py`, test the functions
`create_game`
=> API:  Create a new game when a room is full

conftest.py, hearts/api/games.py, hearts/api/socket_events.py, hearts/api/tests/test_socket_events.py, hearts/game/hearts.py
In this PR:
- Add the ids for the socket connection to the room object.
- Emit the serialized objects for each players
=> api: emit for players

conftest.py, hearts/api/games.py, hearts/api/rest_views.py, hearts/api/socket_events.py, hearts/api/tests/test_socket_events.py, hearts/game/hearts.py, hearts/settings.py, hearts/static/room.js, hearts/static/socket_api.js, hearts/templates/room.html
Blocked by https://github.com/j2kun/lonely-hearts/pull/87
=> frontend: render newly created game

hearts/api/games.py, hearts/api/socket_events.py, hearts/api/tests/setup.py, hearts/api/tests/test_socket_events.py, hearts/game/hearts.py, hearts/game/tests/test_round.py
Implement a socket handler for the `pass_cards` event.
=> backend: pass cards

hearts/api/socket_events.py, hearts/api/strings.py, hearts/api/tests/setup.py, hearts/api/tests/test_socket_events.py, hearts/game/hearts.py
This PR does the following:
1.) Implements the play_card socket event handler
2.) Add notification of cards being passed though the `'receive_cards'` event sent to client
3.) Server sends a `'play_submission_status'` event to client as a confirmation if the card played was valid.
=> Add to play_card and pass_cards

hearts/static/room_client.js, hearts/static/room_socket_client.js, hearts/static/room_state.js, hearts/static/room_ui.js, hearts/templates/room.html
The two fields are provided by the backend.
=> frontend: add messages and mode handling

hearts/api/socket_events.py, hearts/api/tests/test_socket_events.py, hearts/game/hearts.py, hearts/static/room_client.js, hearts/static/room_state.js, hearts/static/room_ui.js
1. As per https://github.com/j2kun/lonely-hearts/issues/99:
- Backend:  Store `messages` and player modes (`player_action`) in each `Round` object.
- Backend: `messages` are serialized so that players can only see their own errors and game prompts.
2. Frontend: When three card are selected, a button appears.  When the button is clicked, the backend updates the `pass_selections` in the `Round`.   
3. Frontend: When the last player clicks the pass card button, the backend emits a game update with updated hands, and the frontend renders it.
=> Frontend mode handling:  Passing Cards

hearts/static/room_client.js, hearts/static/room_socket_client.js, hearts/static/room_state.js, hearts/static/room_ui.js, hearts/templates/room.html
=> frontend: convert all js to camel case

hearts/static/room_ui.js
=> frontend: rewrite trick displaying function
